import React from 'react';

const TypingResult = ({ results, onBack }) => {
  if (!results) return null;

  const handlePrint = () => {
    window.print(); // Isse bacha PDF save kar sakega
  };

  return (
    <div className="min-h-screen bg-gray-50 p-4 md:p-10 font-sans print:bg-white print:p-0">
      <div className="max-w-4xl mx-auto bg-white shadow-2xl rounded-3xl overflow-hidden border border-gray-200 print:shadow-none print:border-none">
        
        {/* Header Section */}
        <div className="bg-blue-600 p-8 text-center text-white print:bg-black">
          <h1 className="text-3xl font-black uppercase tracking-tighter">Typing Test Report Card</h1>
          <p className="text-sm font-bold opacity-80 mt-1 uppercase italic">Official Performance Result</p>
        </div>

        <div className="p-8">
          {/* Main Stats Table */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
            <div className="p-4 bg-blue-50 rounded-2xl border-2 border-blue-100 text-center">
              <p className="text-[10px] font-black text-blue-400 uppercase tracking-widest">Gross Speed</p>
              <p className="text-3xl font-black text-blue-700">{results.grossWpm} <span className="text-xs">WPM</span></p>
            </div>
            <div className="p-4 bg-green-50 rounded-2xl border-2 border-green-100 text-center">
              <p className="text-[10px] font-black text-green-400 uppercase tracking-widest">Net Speed</p>
              <p className="text-3xl font-black text-green-700">{results.netWpm} <span className="text-xs">WPM</span></p>
            </div>
            <div className="p-4 bg-orange-50 rounded-2xl border-2 border-orange-100 text-center">
              <p className="text-[10px] font-black text-orange-400 uppercase tracking-widest">Accuracy</p>
              <p className="text-3xl font-black text-orange-700">{results.accuracy}%</p>
            </div>
            <div className="p-4 bg-red-50 rounded-2xl border-2 border-red-100 text-center">
              <p className="text-[10px] font-black text-red-400 uppercase tracking-widest">Total Errors</p>
              <p className="text-3xl font-black text-red-700">{results.totalErrors}</p>
            </div>
          </div>

          {/* User Info & Matter Details */}
          <div className="flex flex-wrap justify-between text-xs font-bold text-gray-500 uppercase border-b pb-4 mb-6 gap-4">
            <p>Matter: <span className="text-gray-800">{results.matterTitle}</span></p>
            <p>User: <span className="text-gray-800">{results.userName || results.userEmail}</span></p>
            <p>Date: <span className="text-gray-800">{results.submittedAt}</span></p>
          </div>

          {/* Typed Content Area */}
          <div className="mb-8">
            <h3 className="text-sm font-black text-gray-800 uppercase mb-3 italic">Your Typed Content (Final View):</h3>
            <div className="p-6 bg-gray-50 rounded-2xl border border-gray-200 text-lg leading-relaxed font-mono text-gray-700 whitespace-pre-wrap h-80 overflow-y-auto">
              {results.typedContent}
            </div>
            <p className="text-[10px] text-gray-400 mt-2 italic text-right">* All errors were counted as Full Errors as per Sahil's Steno Rules.</p>
          </div>

          {/* Action Buttons (Hidden in Print) */}
          <div className="flex gap-4 print:hidden">
            <button 
              onClick={handlePrint}
              className="flex-1 bg-blue-600 hover:bg-blue-700 text-white py-4 rounded-2xl font-black uppercase text-sm shadow-xl shadow-blue-200 transition-all"
            >
              Download PDF / Print Result
            </button>
            <button 
              onClick={onBack}
              className="flex-1 bg-gray-100 hover:bg-gray-200 text-gray-600 py-4 rounded-2xl font-black uppercase text-sm transition-all"
            >
              Exit to Dashboard
            </button>
          </div>
        </div>

        {/* Footer for Branding */}
        <div className="bg-gray-50 p-4 text-center border-t border-gray-100">
          <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest">Generated by StenoPlus Typing System</p>
        </div>
      </div>
    </div>
  );
};

export default TypingResult;
            
